apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.name }}-secret
type: Opaque
data:
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%d/%s" 
  .Values.database.user 
  .Values.database.password 
  .Values.database.host 
  (.Values.database.port | int64)
  .Values.database.db | b64enc | quote }}
