apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}-cluster-ip
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.database.port }}
      protocol: TCP
  selector:
    components: {{ .Values.database.name }}
