apiVersion: v1
kind: Pod
metadata:
  name: url-shortener-frontend-pod
  labels:
    components: url-shortener-frontend
spec:
  containers:
    - name: url-shortener-frontend-container
      image: antonlarichev/short-app:latest
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
