apiVersion: v1
kind: Service
metadata:
  name: url-shortener-backend-cluster-ip
spec:
  type: ClusterIP
  selector:
    components: url-shortener-backend
  ports:
    - port: 3000
      protocol: TCP
