apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: url-shortener-backend
  template:
    metadata:
      labels:
        components: url-shortener-backend
    spec:
      containers:
        - name: url-shortener-backend-container
          image: antonlarichev/short-api:v1.0
          resources:
            limits:
              memory: "1Gi"
              cpu: "600m"
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: url-shortener-backend-secret
                  key: DATABASE_URL
          volumeMounts:
            - name: test
              mountPath: /etc/test
              readOnly: true
      volumes:
        - name: test
          configMap:
            name: demo-config
