apiVersion: v1
kind: Service
metadata:
  name: url-shortener-postgres-cluster-ip
spec:
  type: ClusterIP
  ports:
    - port: 5432
      protocol: TCP
  selector:
    components: url-shortener-postgres
